import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

const RESEND_API_KEY = Deno.env.get('RESEND_API_KEY');
const FREE2DRIVE_EMAIL = 'info@free2drive.co.nz';

function buildPdfHtml(claim: any, vehicle: any, profile: any, claimNumber: string | null): string {
  const atFaultLabel = claim.at_fault === 'me' ? 'Policyholder at fault' : claim.at_fault === 'other_party' ? 'Other party at fault' : claim.at_fault === 'shared' ? 'Shared fault' : '—';

  const thirdParties = Array.isArray(claim.third_parties) ? claim.third_parties : [];
  let tpHtml = '';
  if (thirdParties.length > 0) {
    tpHtml = '<h2 style="font-size:13px;font-weight:700;color:#1e3a5f;margin:18px 0 6px;text-transform:uppercase;letter-spacing:0.05em;">Third Parties</h2>';
    thirdParties.forEach((tp: any, i: number) => {
      const prefix = thirdParties.length > 1 ? `Party ${i + 1}` : 'Other Party';
      tpHtml += row(`${prefix} – Driver`, tp.ownerName || '—');
      tpHtml += row(`${prefix} – Vehicle`, `${tp.make || ''} ${tp.model || ''} (${tp.regoNumber || ''})`);
      tpHtml += row(`${prefix} – Phone`, tp.phone || '—');
      tpHtml += row(`${prefix} – Insurer`, tp.insurer || '—');
      if (tp.damageDescription) tpHtml += row(`${prefix} – Damage`, tp.damageDescription);
    });
  }

  return `<!DOCTYPE html>
<html><head><meta charset="utf-8"><style>
body{font-family:Helvetica,Arial,sans-serif;color:#1a1a1a;font-size:12px;margin:0;padding:30px;}
h1{font-size:20px;font-weight:700;color:#1e3a5f;margin:0 0 4px;}
h2{font-size:13px;font-weight:700;color:#1e3a5f;margin:18px 0 6px;text-transform:uppercase;letter-spacing:0.05em;}
.meta{font-size:11px;color:#6b7280;margin:0 0 16px;}
.row{display:flex;justify-content:space-between;padding:5px 0;border-bottom:1px solid #f0f0f0;}
.label{color:#6b7280;flex-shrink:0;min-width:140px;}
.value{font-weight:500;text-align:right;word-break:break-word;max-width:55%;}
.footer{margin-top:28px;padding-top:10px;border-top:1px solid #e5e7eb;text-align:center;font-size:10px;color:#9ca3af;}
.highlight{background:#fef3c7;border:1px solid #f59e0b;border-radius:6px;padding:10px 14px;margin:12px 0;}
.highlight strong{color:#92400e;}
</style></head><body>
<h1>SAVO – Courtesy Car Request</h1>
<p class="meta">${claimNumber ? `Claim CLM-${claimNumber} · ` : ''}${claim.incident_date || ''} · ${claim.incident_time || ''}</p>

<div class="highlight"><strong>⚠ Courtesy car requested</strong> – The policyholder is not at fault and has requested a courtesy vehicle.</div>

<h2>Policyholder</h2>
${row('Name', profile?.display_name || '—')}
${row('Email', profile?.email || '—')}
${row('Phone', profile?.phone_number || '—')}
${row('Address', profile?.address || '—')}

<h2>Incident Details</h2>
${row('Date & Time', `${claim.incident_date || '—'} at ${claim.incident_time || '—'}`)}
${row('Location', claim.incident_location || '—')}
${row('Description', claim.description || '—')}
${row('Vehicle Usage', claim.vehicle_usage || '—')}
${row('Journey', claim.journey_details || '—')}

<h2>Vehicle</h2>
${row('Vehicle', vehicle ? `${vehicle.year} ${vehicle.make} ${vehicle.model}` : '—')}
${row('Registration', vehicle?.rego_number || '—')}
${row('Colour', vehicle?.color || '—')}
${row('Insurance Company', claim.insurance_company || vehicle?.insurance_company || '—')}
${row('Policy Number', vehicle?.insurance_policy_number || '—')}

<h2>Damage</h2>
${row('Damage Description', claim.damage_description || '—')}
${row('Speed Before Braking', claim.speed_before_braking ? `${claim.speed_before_braking} km/h` : '—')}
${row('Vehicle Towed', claim.vehicle_towed ? `Yes – ${claim.towing_company || ''}` : 'No')}

<h2>Conditions & Liability</h2>
${row('Weather', claim.weather_condition || '—')}
${row('Road Condition', claim.road_condition || '—')}
${row('At Fault', atFaultLabel)}
${row('Blame Assessment', claim.blame_description || '—')}
${row('Liability Admitted', claim.liability_admitted ? `Yes – ${claim.liability_details || ''}` : 'No')}

${tpHtml}

<h2>Police & Injuries</h2>
${row('Police Attended', claim.police_attended ? `Yes – ${claim.police_officer_details || ''}` : 'No')}
${row('Injuries', claim.anyone_hurt ? claim.injury_details || 'Yes' : 'No')}

<h2>Repairer</h2>
${row('Repairer', claim.repairer_name || '—')}
${row('Phone', claim.repairer_phone || '—')}
${row('Address', claim.repairer_address || '—')}

<div class="footer">Generated by SAVO · savo.co.nz · ${new Date().toLocaleDateString('en-NZ')}</div>
</body></html>`;
}

function row(label: string, value: string): string {
  return `<div class="row"><span class="label">${label}</span><span class="value">${value}</span></div>`;
}

serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    if (!RESEND_API_KEY) throw new Error('RESEND_API_KEY not configured');

    const supabaseUrl = Deno.env.get('SUPABASE_URL')!;
    const supabaseKey = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;
    const supabase = createClient(supabaseUrl, supabaseKey);

    const authHeader = req.headers.get('Authorization');
    if (!authHeader) throw new Error('Missing authorization header');

    const { data: { user }, error: authError } = await supabase.auth.getUser(
      authHeader.replace('Bearer ', '')
    );
    if (authError || !user) throw new Error('Unauthorized');

    const { claimId } = await req.json();
    if (!claimId) throw new Error('Missing claimId');

    // Get claim
    const { data: claim, error: claimErr } = await supabase
      .from('claims')
      .select('*')
      .eq('id', claimId)
      .single();
    if (claimErr || !claim) throw new Error('Claim not found');
    if (claim.user_id !== user.id) throw new Error('Unauthorized');

    // Get vehicle
    const { data: vehicle } = await supabase
      .from('vehicles')
      .select('*')
      .eq('id', claim.vehicle_id)
      .maybeSingle();

    // Get profile
    const { data: profile } = await supabase
      .from('profiles')
      .select('display_name, email, phone_number, address')
      .eq('user_id', user.id)
      .single();

    const claimNumber = claim.claim_number ? String(claim.claim_number).padStart(4, '0') : null;

    // Generate HTML for PDF
    const pdfHtml = buildPdfHtml(claim, vehicle, profile, claimNumber);

    // Use Lovable API to convert HTML to PDF
    const LOVABLE_API_KEY = Deno.env.get('LOVABLE_API_KEY');
    
    // Since we can't generate PDF server-side easily in Deno, send as HTML email with all details
    // and attach the HTML as a styled report
    const emailSubject = `Courtesy Car Request – ${claimNumber ? `CLM-${claimNumber}` : claimId.slice(0, 8).toUpperCase()} – ${profile?.display_name || 'SAVO User'}`;

    const emailHtml = `
      <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
        <div style="background: #1e3a5f; padding: 20px; border-radius: 8px 8px 0 0;">
          <h1 style="color: #ffffff; margin: 0; font-size: 18px;">🚗 Courtesy Car Request</h1>
          <p style="color: #94a3b8; margin: 4px 0 0; font-size: 13px;">via SAVO – Vehicle Claims Assistant</p>
        </div>
        <div style="padding: 20px; background: #f8fafc; border: 1px solid #e2e8f0;">
          <div style="background: #fef3c7; border: 1px solid #f59e0b; border-radius: 6px; padding: 12px 16px; margin-bottom: 16px;">
            <strong style="color: #92400e;">Courtesy car requested</strong>
            <p style="color: #92400e; margin: 4px 0 0; font-size: 13px;">The policyholder is not at fault and has requested a courtesy vehicle while theirs is being repaired.</p>
          </div>
          
          <h3 style="color: #1e3a5f; font-size: 14px; margin: 16px 0 8px; border-bottom: 1px solid #e2e8f0; padding-bottom: 4px;">Policyholder</h3>
          <table style="width: 100%; font-size: 13px; border-collapse: collapse;">
            <tr><td style="padding: 4px 0; color: #6b7280; width: 140px;">Name</td><td style="padding: 4px 0; font-weight: 500;">${profile?.display_name || '—'}</td></tr>
            <tr><td style="padding: 4px 0; color: #6b7280;">Email</td><td style="padding: 4px 0;">${profile?.email || user.email || '—'}</td></tr>
            <tr><td style="padding: 4px 0; color: #6b7280;">Phone</td><td style="padding: 4px 0;">${profile?.phone_number || '—'}</td></tr>
            <tr><td style="padding: 4px 0; color: #6b7280;">Address</td><td style="padding: 4px 0;">${profile?.address || '—'}</td></tr>
          </table>

          <h3 style="color: #1e3a5f; font-size: 14px; margin: 16px 0 8px; border-bottom: 1px solid #e2e8f0; padding-bottom: 4px;">Vehicle</h3>
          <table style="width: 100%; font-size: 13px; border-collapse: collapse;">
            <tr><td style="padding: 4px 0; color: #6b7280; width: 140px;">Vehicle</td><td style="padding: 4px 0; font-weight: 500;">${vehicle ? `${vehicle.year} ${vehicle.make} ${vehicle.model}` : '—'}</td></tr>
            <tr><td style="padding: 4px 0; color: #6b7280;">Registration</td><td style="padding: 4px 0;">${vehicle?.rego_number || '—'}</td></tr>
            <tr><td style="padding: 4px 0; color: #6b7280;">Colour</td><td style="padding: 4px 0;">${vehicle?.color || '—'}</td></tr>
            <tr><td style="padding: 4px 0; color: #6b7280;">Insurance</td><td style="padding: 4px 0;">${claim.insurance_company || vehicle?.insurance_company || '—'}</td></tr>
            <tr><td style="padding: 4px 0; color: #6b7280;">Policy #</td><td style="padding: 4px 0;">${vehicle?.insurance_policy_number || '—'}</td></tr>
          </table>

          <h3 style="color: #1e3a5f; font-size: 14px; margin: 16px 0 8px; border-bottom: 1px solid #e2e8f0; padding-bottom: 4px;">Incident</h3>
          <table style="width: 100%; font-size: 13px; border-collapse: collapse;">
            <tr><td style="padding: 4px 0; color: #6b7280; width: 140px;">Date & Time</td><td style="padding: 4px 0;">${claim.incident_date || '—'} at ${claim.incident_time || '—'}</td></tr>
            <tr><td style="padding: 4px 0; color: #6b7280;">Location</td><td style="padding: 4px 0;">${claim.incident_location || '—'}</td></tr>
            <tr><td style="padding: 4px 0; color: #6b7280;">Description</td><td style="padding: 4px 0;">${claim.description || '—'}</td></tr>
            <tr><td style="padding: 4px 0; color: #6b7280;">Damage</td><td style="padding: 4px 0;">${claim.damage_description || '—'}</td></tr>
            <tr><td style="padding: 4px 0; color: #6b7280;">Fault</td><td style="padding: 4px 0;">Other party at fault</td></tr>
          </table>

          ${claimNumber ? `<p style="margin-top: 16px; font-size: 12px; color: #6b7280;">Claim Reference: CLM-${claimNumber}</p>` : ''}
        </div>
        <div style="padding: 16px 20px; background: #f1f5f9; border-radius: 0 0 8px 8px; border: 1px solid #e2e8f0; border-top: 0;">
          <p style="color: #94a3b8; font-size: 11px; margin: 0;">Sent via <strong>SAVO</strong> · savo.co.nz</p>
        </div>
      </div>`;

    // Send via Resend
    const res = await fetch('https://api.resend.com/emails', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${RESEND_API_KEY}`,
      },
      body: JSON.stringify({
        from: 'SAVO Claims <claims@savo.co.nz>',
        to: [FREE2DRIVE_EMAIL],
        subject: emailSubject,
        html: emailHtml,
      }),
    });

    const result = await res.json();
    if (!res.ok) throw new Error(`Resend error: ${JSON.stringify(result)}`);

    console.log(`Courtesy car email sent to ${FREE2DRIVE_EMAIL} for claim ${claimId}`);

    return new Response(JSON.stringify({ success: true, messageId: result.id }), {
      status: 200,
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    });
  } catch (error: unknown) {
    const message = error instanceof Error ? error.message : 'Unknown error';
    console.error('Courtesy car email error:', message);
    return new Response(JSON.stringify({ success: false, error: message }), {
      status: 500,
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    });
  }
});
